/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { AccountResponse } from "./accountResponse";
import { OAuthTokenResponse } from "./oAuthTokenResponse";
import { WarningResponse } from "./warningResponse";

export class AccountCreateResponse {
  "account"?: AccountResponse;
  "oauthData"?: OAuthTokenResponse;
  /**
   * A list of warnings.
   */
  "warnings"?: Array<WarningResponse>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "account",
      baseName: "account",
      type: "AccountResponse",
    },
    {
      name: "oauthData",
      baseName: "oauth_data",
      type: "OAuthTokenResponse",
    },
    {
      name: "warnings",
      baseName: "warnings",
      type: "Array<WarningResponse>",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return AccountCreateResponse.attributeTypeMap;
  }
}
