/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

/**
 * An object with options to customize the app\'s signer page
 */
export class ApiAppResponseWhiteLabelingOptions {
  "headerBackgroundColor"?: string;
  "legalVersion"?: string;
  "linkColor"?: string;
  "pageBackgroundColor"?: string;
  "primaryButtonColor"?: string;
  "primaryButtonColorHover"?: string;
  "primaryButtonTextColor"?: string;
  "primaryButtonTextColorHover"?: string;
  "secondaryButtonColor"?: string;
  "secondaryButtonColorHover"?: string;
  "secondaryButtonTextColor"?: string;
  "secondaryButtonTextColorHover"?: string;
  "textColor1"?: string;
  "textColor2"?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "headerBackgroundColor",
      baseName: "header_background_color",
      type: "string",
    },
    {
      name: "legalVersion",
      baseName: "legal_version",
      type: "string",
    },
    {
      name: "linkColor",
      baseName: "link_color",
      type: "string",
    },
    {
      name: "pageBackgroundColor",
      baseName: "page_background_color",
      type: "string",
    },
    {
      name: "primaryButtonColor",
      baseName: "primary_button_color",
      type: "string",
    },
    {
      name: "primaryButtonColorHover",
      baseName: "primary_button_color_hover",
      type: "string",
    },
    {
      name: "primaryButtonTextColor",
      baseName: "primary_button_text_color",
      type: "string",
    },
    {
      name: "primaryButtonTextColorHover",
      baseName: "primary_button_text_color_hover",
      type: "string",
    },
    {
      name: "secondaryButtonColor",
      baseName: "secondary_button_color",
      type: "string",
    },
    {
      name: "secondaryButtonColorHover",
      baseName: "secondary_button_color_hover",
      type: "string",
    },
    {
      name: "secondaryButtonTextColor",
      baseName: "secondary_button_text_color",
      type: "string",
    },
    {
      name: "secondaryButtonTextColorHover",
      baseName: "secondary_button_text_color_hover",
      type: "string",
    },
    {
      name: "textColor1",
      baseName: "text_color1",
      type: "string",
    },
    {
      name: "textColor2",
      baseName: "text_color2",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return ApiAppResponseWhiteLabelingOptions.attributeTypeMap;
  }
}
