/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { ApiAppResponseOAuth } from "./apiAppResponseOAuth";
import { ApiAppResponseOptions } from "./apiAppResponseOptions";
import { ApiAppResponseOwnerAccount } from "./apiAppResponseOwnerAccount";
import { ApiAppResponseWhiteLabelingOptions } from "./apiAppResponseWhiteLabelingOptions";
import { WarningResponse } from "./warningResponse";

export class ApiAppResponse {
  /**
   * The app\'s callback URL (for events)
   */
  "callbackUrl"?: string | null;
  /**
   * The app\'s client ID
   */
  "clientId"?: string;
  /**
   * The time that the app was created
   */
  "createdAt"?: number;
  /**
   * The domain name associated with the app
   */
  "domain"?: string;
  /**
   * The name of the app
   */
  "name"?: string;
  /**
   * Boolean to indicate if the app has been approved
   */
  "isApproved"?: boolean;
  "oauth"?: ApiAppResponseOAuth | null;
  "options"?: ApiAppResponseOptions | null;
  "ownerAccount"?: ApiAppResponseOwnerAccount;
  "whiteLabelingOptions"?: ApiAppResponseWhiteLabelingOptions;
  "warnings"?: Array<WarningResponse>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "callbackUrl",
      baseName: "callback_url",
      type: "string",
    },
    {
      name: "clientId",
      baseName: "client_id",
      type: "string",
    },
    {
      name: "createdAt",
      baseName: "created_at",
      type: "number",
    },
    {
      name: "domain",
      baseName: "domain",
      type: "string",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "isApproved",
      baseName: "is_approved",
      type: "boolean",
    },
    {
      name: "oauth",
      baseName: "oauth",
      type: "ApiAppResponseOAuth",
    },
    {
      name: "options",
      baseName: "options",
      type: "ApiAppResponseOptions",
    },
    {
      name: "ownerAccount",
      baseName: "owner_account",
      type: "ApiAppResponseOwnerAccount",
    },
    {
      name: "whiteLabelingOptions",
      baseName: "white_labeling_options",
      type: "ApiAppResponseWhiteLabelingOptions",
    },
    {
      name: "warnings",
      baseName: "warnings",
      type: "Array<WarningResponse>",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return ApiAppResponse.attributeTypeMap;
  }
}
