/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

/**
 * An object with options that override account settings.
 */
export class ApiAppResponseOptions {
  /**
   * Boolean denoting if signers can \"Insert Everywhere\" in one click while signing a document
   */
  "canInsertEverywhere"?: boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "canInsertEverywhere",
      baseName: "can_insert_everywhere",
      type: "boolean",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return ApiAppResponseOptions.attributeTypeMap;
  }
}
