/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { WarningResponse } from "./warningResponse";

export class BulkSendJobResponse {
  /**
   * The id of the BulkSendJob.
   */
  "bulkSendJobId"?: string | null;
  /**
   * The total amount of SignatureRequests queued for sending.
   */
  "total"?: number;
  /**
   * True if you are the owner of this BulkSendJob, false if it\'s been shared with you by a team member.
   */
  "isCreator"?: boolean;
  /**
   * Time that the BulkSendJob was created.
   */
  "createdAt"?: number;
  "warnings"?: Array<WarningResponse>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "bulkSendJobId",
      baseName: "bulk_send_job_id",
      type: "string",
    },
    {
      name: "total",
      baseName: "total",
      type: "number",
    },
    {
      name: "isCreator",
      baseName: "is_creator",
      type: "boolean",
    },
    {
      name: "createdAt",
      baseName: "created_at",
      type: "number",
    },
    {
      name: "warnings",
      baseName: "warnings",
      type: "Array<WarningResponse>",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return BulkSendJobResponse.attributeTypeMap;
  }
}
