/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

/**
 * An embedded template object.
 */
export class EmbeddedEditUrlResponseEmbedded {
  /**
   * A template url that can be opened in an iFrame.
   */
  "editUrl"?: string;
  /**
   * The specific time that the the `edit_url` link expires, in epoch.
   */
  "expiresAt"?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "editUrl",
      baseName: "edit_url",
      type: "string",
    },
    {
      name: "expiresAt",
      baseName: "expires_at",
      type: "number",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return EmbeddedEditUrlResponseEmbedded.attributeTypeMap;
  }
}
