/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { ErrorResponseError } from "./errorResponseError";

export class ErrorResponse {
  "error": ErrorResponseError;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "error",
      baseName: "error",
      type: "ErrorResponseError",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return ErrorResponse.attributeTypeMap;
  }
}
