/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

export class ErrorResponse {
  "errorMsg": string;
  "errorName": string;
  "errorPath"?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "errorMsg",
      baseName: "error_msg",
      type: "string",
    },
    {
      name: "errorName",
      baseName: "error_name",
      type: "string",
    },
    {
      name: "errorPath",
      baseName: "error_path",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return ErrorResponse.attributeTypeMap;
  }
}
