/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

/**
 * Specific metadata about the event.
 */
export class EventCallbackRequestEventMetadata {
  /**
   * Signature ID for a specific signer. Applicable to `signature_request_signed` and `signature_request_viewed` events.
   */
  "relatedSignatureId"?: string | null;
  /**
   * Account ID the event was reported for.
   */
  "reportedForAccountId"?: string | null;
  /**
   * App ID the event was reported for.
   */
  "reportedForAppId"?: string | null;
  /**
   * Message about a declined or failed (due to error) signature flow.
   */
  "eventMessage"?: string | null;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "relatedSignatureId",
      baseName: "related_signature_id",
      type: "string",
    },
    {
      name: "reportedForAccountId",
      baseName: "reported_for_account_id",
      type: "string",
    },
    {
      name: "reportedForAppId",
      baseName: "reported_for_app_id",
      type: "string",
    },
    {
      name: "eventMessage",
      baseName: "event_message",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return EventCallbackRequestEventMetadata.attributeTypeMap;
  }
}
