/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { EventCallbackRequestEvent } from "./eventCallbackRequestEvent";
import { SignatureRequestResponse } from "./signatureRequestResponse";
import { TemplateResponse } from "./templateResponse";

export class EventCallbackAccountRequestPayload {
  "event": EventCallbackRequestEvent;
  "accountGuid"?: string;
  "clientId"?: string | null;
  "signatureRequest"?: SignatureRequestResponse;
  "template"?: TemplateResponse;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "event",
      baseName: "event",
      type: "EventCallbackRequestEvent",
    },
    {
      name: "accountGuid",
      baseName: "account_guid",
      type: "string",
    },
    {
      name: "clientId",
      baseName: "client_id",
      type: "string",
    },
    {
      name: "signatureRequest",
      baseName: "signature_request",
      type: "SignatureRequestResponse",
    },
    {
      name: "template",
      baseName: "template",
      type: "TemplateResponse",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return EventCallbackAccountRequestPayload.attributeTypeMap;
  }
}
