/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

/**
 * Contains pagination information about the data returned.
 */
export class ListInfoResponse {
  /**
   * Total number of pages available.
   */
  "numPages"?: number;
  /**
   * Total number of objects available.
   */
  "numResults"?: number | null;
  /**
   * Number of the page being returned.
   */
  "page"?: number;
  /**
   * Objects returned per page.
   */
  "pageSize"?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "numPages",
      baseName: "num_pages",
      type: "number",
    },
    {
      name: "numResults",
      baseName: "num_results",
      type: "number",
    },
    {
      name: "page",
      baseName: "page",
      type: "number",
    },
    {
      name: "pageSize",
      baseName: "page_size",
      type: "number",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return ListInfoResponse.attributeTypeMap;
  }
}
