/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

export class ReportCreateRequest {
  /**
   * The (inclusive) end date for the report data in `MM/DD/YYYY` format.
   */
  "endDate": string;
  /**
   * The type(s) of the report you are requesting. Allowed values are `user_activity` and `document_status`. User activity reports contain list of all users and their activity during the specified date range. Document status report contain a list of signature requests created in the specified time range (and their status).
   */
  "reportType": Array<ReportCreateRequest.ReportTypeEnum>;
  /**
   * The (inclusive) start date for the report data in `MM/DD/YYYY` format.
   */
  "startDate": string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "endDate",
      baseName: "end_date",
      type: "string",
    },
    {
      name: "reportType",
      baseName: "report_type",
      type: "Array<ReportCreateRequest.ReportTypeEnum>",
    },
    {
      name: "startDate",
      baseName: "start_date",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return ReportCreateRequest.attributeTypeMap;
  }
}

export namespace ReportCreateRequest {
  export enum ReportTypeEnum {
    UserActivity = "user_activity",
    DocumentStatus = "document_status",
  }
}
