/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { SignatureRequestResponse } from "./signatureRequestResponse";

export class SignatureRequestGetResponse {
  "signatureRequest"?: SignatureRequestResponse;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "signatureRequest",
      baseName: "signature_request",
      type: "SignatureRequestResponse",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return SignatureRequestGetResponse.attributeTypeMap;
  }
}
