/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

/**
 * An array of signature objects, 1 for each signer.
 */
export class SignatureRequestResponseSignatures {
  /**
   * Signature identifier.
   */
  "signatureId"?: string;
  /**
   * The email address of the signer.
   */
  "signerEmailAddress"?: string;
  /**
   * The name of the signer.
   */
  "signerName"?: string;
  /**
   * The role of the signer.
   */
  "signerRole"?: string | null;
  /**
   * If signer order is assigned this is the 0-based index for this signer.
   */
  "order"?: number | null;
  /**
   * The current status of the signature. eg: awaiting_signature, signed, declined.
   */
  "statusCode"?: string;
  /**
   * The reason provided by the signer for declining the request.
   */
  "declineReason"?: string | null;
  /**
   * Time that the document was signed or null.
   */
  "signedAt"?: number | null;
  /**
   * The time that the document was last viewed by this signer or null.
   */
  "lastViewedAt"?: number | null;
  /**
   * The time the last reminder email was sent to the signer or null.
   */
  "lastRemindedAt"?: number | null;
  /**
   * Boolean to indicate whether this signature requires a PIN to access.
   */
  "hasPin"?: boolean;
  /**
   * Boolean to indicate whether this signature has SMS authentication enabled.
   */
  "hasSmsAuth"?: boolean | null;
  /**
   * Boolean to indicate whether this signature has SMS delivery enabled.
   */
  "hasSmsDelivery"?: boolean | null;
  /**
   * The SMS phone number used for authentication or signature request delivery.
   */
  "smsPhoneNumber"?: string | null;
  /**
   * Email address of original signer who reassigned to this signer.
   */
  "reassignedBy"?: string | null;
  /**
   * Reason provided by original signer who reassigned to this signer.
   */
  "reassignmentReason"?: string | null;
  /**
   * Error message pertaining to this signer, or null.
   */
  "error"?: string | null;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "signatureId",
      baseName: "signature_id",
      type: "string",
    },
    {
      name: "signerEmailAddress",
      baseName: "signer_email_address",
      type: "string",
    },
    {
      name: "signerName",
      baseName: "signer_name",
      type: "string",
    },
    {
      name: "signerRole",
      baseName: "signer_role",
      type: "string",
    },
    {
      name: "order",
      baseName: "order",
      type: "number",
    },
    {
      name: "statusCode",
      baseName: "status_code",
      type: "string",
    },
    {
      name: "declineReason",
      baseName: "decline_reason",
      type: "string",
    },
    {
      name: "signedAt",
      baseName: "signed_at",
      type: "number",
    },
    {
      name: "lastViewedAt",
      baseName: "last_viewed_at",
      type: "number",
    },
    {
      name: "lastRemindedAt",
      baseName: "last_reminded_at",
      type: "number",
    },
    {
      name: "hasPin",
      baseName: "has_pin",
      type: "boolean",
    },
    {
      name: "hasSmsAuth",
      baseName: "has_sms_auth",
      type: "boolean",
    },
    {
      name: "hasSmsDelivery",
      baseName: "has_sms_delivery",
      type: "boolean",
    },
    {
      name: "smsPhoneNumber",
      baseName: "sms_phone_number",
      type: "string",
    },
    {
      name: "reassignedBy",
      baseName: "reassigned_by",
      type: "string",
    },
    {
      name: "reassignmentReason",
      baseName: "reassignment_reason",
      type: "string",
    },
    {
      name: "error",
      baseName: "error",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return SignatureRequestResponseSignatures.attributeTypeMap;
  }
}
