/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

/**
 * An array of Custom Field objects containing the name and type of each custom field.  * Text Field uses `SignatureRequestResponseCustomFieldText` * Checkbox Field uses `SignatureRequestResponseCustomFieldCheckbox`
 */
export abstract class SignatureRequestResponseCustomFieldBase {
  /**
   * The type of this Custom Field. Only \'text\' and \'checkbox\' are currently supported.
   */
  "type": string;
  /**
   * The name of the Custom Field.
   */
  "name": string;
  /**
   * A boolean value denoting if this field is required.
   */
  "required"?: boolean;
  /**
   * The unique ID for this field.
   */
  "apiId"?: string;
  /**
   * The name of the Role that is able to edit this field.
   */
  "editor"?: string;

  static discriminator: string | undefined = "type";

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "type",
      baseName: "type",
      type: "string",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "required",
      baseName: "required",
      type: "boolean",
    },
    {
      name: "apiId",
      baseName: "api_id",
      type: "string",
    },
    {
      name: "editor",
      baseName: "editor",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return SignatureRequestResponseCustomFieldBase.attributeTypeMap;
  }

  static discriminatorClassName(value: any): string | null {
    if (value === undefined || value === null) {
      return null;
    }

    if (value === "checkbox") {
      return "SignatureRequestResponseCustomFieldCheckbox";
    }
    if (value === "text") {
      return "SignatureRequestResponseCustomFieldText";
    }

    return null;
  }
}
