/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { SignatureRequestResponseCustomFieldBase } from "./signatureRequestResponseCustomFieldBase";

/**
 * This class extends `SignatureRequestResponseCustomFieldBase`.
 */
export class SignatureRequestResponseCustomFieldCheckbox extends SignatureRequestResponseCustomFieldBase {
  /**
   * The type of this Custom Field. Only \'text\' and \'checkbox\' are currently supported.
   */
  "type": string = "checkbox";
  /**
   * A true/false for checkbox fields
   */
  "value"?: boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "type",
      baseName: "type",
      type: "string",
    },
    {
      name: "value",
      baseName: "value",
      type: "boolean",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return super
      .getAttributeTypeMap()
      .concat(SignatureRequestResponseCustomFieldCheckbox.attributeTypeMap);
  }
}
