/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { SignatureRequestResponseDataBase } from "./signatureRequestResponseDataBase";

export class SignatureRequestResponseDataValueCheckboxMerge extends SignatureRequestResponseDataBase {
  /**
   * A checkbox field that has default value set by the api
   */
  "type"?: string = "checkbox-merge";
  /**
   * The value of the form field.
   */
  "value"?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "type",
      baseName: "type",
      type: "string",
    },
    {
      name: "value",
      baseName: "value",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return super
      .getAttributeTypeMap()
      .concat(SignatureRequestResponseDataValueCheckboxMerge.attributeTypeMap);
  }
}
