/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

export enum SignatureRequestResponseDataTypeEnum {
  Text = "text",
  Checkbox = "checkbox",
  DateSigned = "date_signed",
  Dropdown = "dropdown",
  Initials = "initials",
  Radio = "radio",
  Signature = "signature",
  TextMerge = "text-merge",
  CheckboxMerge = "checkbox-merge",
}
