/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

/**
 * Signer attachments.
 */
export class SignatureRequestResponseAttachment {
  /**
   * The unique ID for this attachment.
   */
  "id": string;
  /**
   * The Signer this attachment is assigned to.
   */
  "signer": string;
  /**
   * The name of this attachment.
   */
  "name": string;
  /**
   * A boolean value denoting if this attachment is required.
   */
  "required": boolean;
  /**
   * Instructions for Signer.
   */
  "instructions"?: string | null;
  /**
   * Timestamp when attachment was uploaded by Signer.
   */
  "uploadedAt"?: number | null;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "id",
      baseName: "id",
      type: "string",
    },
    {
      name: "signer",
      baseName: "signer",
      type: "string",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "required",
      baseName: "required",
      type: "boolean",
    },
    {
      name: "instructions",
      baseName: "instructions",
      type: "string",
    },
    {
      name: "uploadedAt",
      baseName: "uploaded_at",
      type: "number",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return SignatureRequestResponseAttachment.attributeTypeMap;
  }
}
