/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

/**
 * An array of form field objects containing the name, value, and type of each textbox or checkmark field filled in by the signers.
 */
export class SignatureRequestResponseData {
  /**
   * The unique ID for this field.
   */
  "apiId"?: string;
  /**
   * The ID of the signature to which this response is linked.
   */
  "signatureId"?: string;
  /**
   * The name of the form field.
   */
  "name"?: string;
  /**
   * The value of the form field.
   */
  "value"?: string;
  /**
   * A boolean value denoting if this field is required.
   */
  "required"?: boolean;
  /**
   * - `text`: A text input field - `checkbox`: A yes/no checkbox - `date_signed`: A date - `dropdown`: An input field for dropdowns - `initials`: An input field for initials - `radio`: An input field for radios - `signature`: A signature input field - `text-merge`: A text field that has default text set by the api - `checkbox-merge`: A checkbox field that has default value set by the api
   */
  "type"?: SignatureRequestResponseData.TypeEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "apiId",
      baseName: "api_id",
      type: "string",
    },
    {
      name: "signatureId",
      baseName: "signature_id",
      type: "string",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "value",
      baseName: "value",
      type: "string",
    },
    {
      name: "required",
      baseName: "required",
      type: "boolean",
    },
    {
      name: "type",
      baseName: "type",
      type: "SignatureRequestResponseData.TypeEnum",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return SignatureRequestResponseData.attributeTypeMap;
  }
}

export namespace SignatureRequestResponseData {
  export enum TypeEnum {
    Text = "text",
    Checkbox = "checkbox",
    DateSigned = "date_signed",
    Dropdown = "dropdown",
    Initials = "initials",
    Radio = "radio",
    Signature = "signature",
    TextMerge = "text-merge",
    CheckboxMerge = "checkbox-merge",
  }
}
