/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

export class SignatureRequestRemindRequest {
  /**
   * The email address of the signer to send a reminder to.
   */
  "emailAddress": string;
  /**
   * The name of the signer to send a reminder to. Include if two or more signers share an email address.
   */
  "name"?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "emailAddress",
      baseName: "email_address",
      type: "string",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return SignatureRequestRemindRequest.attributeTypeMap;
  }
}
