/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

export class SubAttachment {
  /**
   * The name of attachment.
   */
  "name": string;
  /**
   * The signer\'s index in the `signers` parameter (0-based indexing).  **NOTE**: Only one signer can be assigned per attachment.
   */
  "signerIndex": number;
  /**
   * The instructions for uploading the attachment.
   */
  "instructions"?: string;
  /**
   * Determines if the attachment must be uploaded.
   */
  "required"?: boolean = false;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "signerIndex",
      baseName: "signer_index",
      type: "number",
    },
    {
      name: "instructions",
      baseName: "instructions",
      type: "string",
    },
    {
      name: "required",
      baseName: "required",
      type: "boolean",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return SubAttachment.attributeTypeMap;
  }
}
