/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { SubBulkSignerListCustomField } from "./subBulkSignerListCustomField";
import { SubSignatureRequestTemplateSigner } from "./subSignatureRequestTemplateSigner";

export class SubBulkSignerList {
  /**
   * An array of custom field values.
   */
  "customFields"?: Array<SubBulkSignerListCustomField>;
  /**
   * Add Signers to your Templated-based Signature Request. Allows the requester to specify editor options when a preparing a document.  Currently only templates with a single role are supported. All signers must have the same `role` value.
   */
  "signers"?: Array<SubSignatureRequestTemplateSigner>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "customFields",
      baseName: "custom_fields",
      type: "Array<SubBulkSignerListCustomField>",
    },
    {
      name: "signers",
      baseName: "signers",
      type: "Array<SubSignatureRequestTemplateSigner>",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return SubBulkSignerList.attributeTypeMap;
  }
}
