/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { SubFormFieldsPerDocumentBase } from "./subFormFieldsPerDocumentBase";

/**
 * This class extends `SubFormFieldsPerDocumentBase`.
 */
export class SubFormFieldsPerDocumentHyperlink extends SubFormFieldsPerDocumentBase {
  /**
   * A hyperlink field. Use the `SubFormFieldsPerDocumentHyperlink` class.
   */
  "type": string = "hyperlink";
  /**
   * Link Text.
   */
  "content": string;
  /**
   * Link URL.
   */
  "contentUrl": string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "type",
      baseName: "type",
      type: "string",
    },
    {
      name: "content",
      baseName: "content",
      type: "string",
    },
    {
      name: "contentUrl",
      baseName: "content_url",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return super
      .getAttributeTypeMap()
      .concat(SubFormFieldsPerDocumentHyperlink.attributeTypeMap);
  }
}
