/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { SubFormFieldsPerDocumentBase } from "./subFormFieldsPerDocumentBase";

/**
 * This class extends `SubFormFieldsPerDocumentBase`.
 */
export class SubFormFieldsPerDocumentRadio extends SubFormFieldsPerDocumentBase {
  /**
   * An input field for radios. Use the `SubFormFieldsPerDocumentRadio` class.
   */
  "type": string = "radio";
  /**
   * String referencing group defined in `form_field_groups` parameter.
   */
  "group": string;
  /**
   * `true` for checking the radio field by default, otherwise `false`. Only one radio field per group can be `true`.
   */
  "isChecked": boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "type",
      baseName: "type",
      type: "string",
    },
    {
      name: "group",
      baseName: "group",
      type: "string",
    },
    {
      name: "isChecked",
      baseName: "is_checked",
      type: "boolean",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return super
      .getAttributeTypeMap()
      .concat(SubFormFieldsPerDocumentRadio.attributeTypeMap);
  }
}
