/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

export class SubOAuth {
  /**
   * The callback URL to be used for OAuth flows. (Required if `oauth[scopes]` is provided)
   */
  "callbackUrl"?: string;
  /**
   * A list of OAuth scopes to be granted to the app. (Required if `oauth[callback_url]` is provided).
   */
  "scopes"?: Array<SubOAuth.ScopesEnum>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "callbackUrl",
      baseName: "callback_url",
      type: "string",
    },
    {
      name: "scopes",
      baseName: "scopes",
      type: "Array<SubOAuth.ScopesEnum>",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return SubOAuth.attributeTypeMap;
  }
}

export namespace SubOAuth {
  export enum ScopesEnum {
    AccessDocs = "access_docs",
    AccessReusableForms = "access_reusable_forms",
    ManageDocs = "manage_docs",
    RequestSignature = "request_signature",
    SendDocs = "send_docs",
    BasicAccountInfo = "basic_account_info",
    Signatures = "signatures",
    AccountAccess = "account_access",
    SignatureRequestAccess = "signature_request_access",
    TemplateAccess = "template_access",
    TeamAccess = "team_access",
    ApiAppAccess = "api_app_access",
    UniversalSignatureRequestAccess = "universal_signature_request_access",
    Empty = "",
  }
}
