/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

export class SubSignatureRequestSigner {
  /**
   * The name of the signer.
   */
  "name": string;
  /**
   * The email address of the signer.
   */
  "emailAddress": string;
  /**
   * The order the signer is required to sign in.
   */
  "order"?: number | null;
  /**
   * The 4- to 12-character access code that will secure this signer\'s signature page.
   */
  "pin"?: string;
  /**
   * An E.164 formatted phone number.  **Note**: Not available in test mode and requires a Standard plan or higher.
   */
  "smsPhoneNumber"?: string;
  /**
   * **Note**: This only works in non embedded endpoints.  If set, the value must be either `authentication` or `delivery`. Default `authentication`.   If `authentication` is set, `sms_phone_number` will receive a code via SMS to access this signer\'s signature page.  If `delivery` is set, signature request will be delivered to both email and `sms_phone_number`.
   */
  "smsPhoneNumberType"?: SubSignatureRequestSigner.SmsPhoneNumberTypeEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "emailAddress",
      baseName: "email_address",
      type: "string",
    },
    {
      name: "order",
      baseName: "order",
      type: "number",
    },
    {
      name: "pin",
      baseName: "pin",
      type: "string",
    },
    {
      name: "smsPhoneNumber",
      baseName: "sms_phone_number",
      type: "string",
    },
    {
      name: "smsPhoneNumberType",
      baseName: "sms_phone_number_type",
      type: "SubSignatureRequestSigner.SmsPhoneNumberTypeEnum",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return SubSignatureRequestSigner.attributeTypeMap;
  }
}

export namespace SubSignatureRequestSigner {
  export enum SmsPhoneNumberTypeEnum {
    Authentication = "authentication",
    Delivery = "delivery",
  }
}
