/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

export class SubTemplateRole {
  /**
   * The role name of the signer that will be displayed when the template is used to create a signature request.
   */
  "name"?: string;
  /**
   * The order in which this signer role is required to sign.
   */
  "order"?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "order",
      baseName: "order",
      type: "number",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return SubTemplateRole.attributeTypeMap;
  }
}
