/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

export class SubUnclaimedDraftEmbeddedTemplateSigner {
  /**
   * Must match an existing role in chosen Template(s). Multiple signers cannot share the same `role`.
   */
  "role": string;
  /**
   * The name of the signer filling the role of `role`.
   */
  "name": string;
  /**
   * The email address of the signer filling the role of `role`.
   */
  "emailAddress": string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "role",
      baseName: "role",
      type: "string",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "emailAddress",
      baseName: "email_address",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return SubUnclaimedDraftEmbeddedTemplateSigner.attributeTypeMap;
  }
}
