/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { ListInfoResponse } from "./listInfoResponse";
import { TeamMemberResponse } from "./teamMemberResponse";
import { WarningResponse } from "./warningResponse";

export class TeamMembersResponse {
  /**
   * Contains a list of team members and their roles for a specific team.
   */
  "teamMembers"?: Array<TeamMemberResponse>;
  "listInfo"?: ListInfoResponse;
  "warnings"?: Array<WarningResponse>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "teamMembers",
      baseName: "team_members",
      type: "Array<TeamMemberResponse>",
    },
    {
      name: "listInfo",
      baseName: "list_info",
      type: "ListInfoResponse",
    },
    {
      name: "warnings",
      baseName: "warnings",
      type: "Array<WarningResponse>",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return TeamMembersResponse.attributeTypeMap;
  }
}
