/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

export class TeamRemoveMemberRequest {
  /**
   * **account_id** or **email_address** is required. If both are provided, the account id prevails.   Account id to remove from your Team.
   */
  "accountId"?: string;
  /**
   * **account_id** or **email_address** is required. If both are provided, the account id prevails.   Email address of the Account to remove from your Team.
   */
  "emailAddress"?: string;
  /**
   * The email address of an Account on this Team to receive all documents, templates, and API apps (if applicable) from the removed Account. If not provided, and on an Enterprise plan, this data will remain with the removed Account.  **Note**: Only available for Enterprise plans.
   */
  "newOwnerEmailAddress"?: string;
  /**
   * Id of the new Team.
   */
  "newTeamId"?: string;
  /**
   * A new role member will take in a new Team.  **Note**: This parameter is used only if `new_team_id` is provided.
   */
  "newRole"?: TeamRemoveMemberRequest.NewRoleEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "accountId",
      baseName: "account_id",
      type: "string",
    },
    {
      name: "emailAddress",
      baseName: "email_address",
      type: "string",
    },
    {
      name: "newOwnerEmailAddress",
      baseName: "new_owner_email_address",
      type: "string",
    },
    {
      name: "newTeamId",
      baseName: "new_team_id",
      type: "string",
    },
    {
      name: "newRole",
      baseName: "new_role",
      type: "TeamRemoveMemberRequest.NewRoleEnum",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return TeamRemoveMemberRequest.attributeTypeMap;
  }
}

export namespace TeamRemoveMemberRequest {
  export enum NewRoleEnum {
    Member = "Member",
    Developer = "Developer",
    TeamManager = "Team Manager",
    Admin = "Admin",
  }
}
