/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

export class TeamAddMemberRequest {
  /**
   * `account_id` or `email_address` is required. If both are provided, the account id prevails.   Account id of the user to invite to your Team.
   */
  "accountId"?: string;
  /**
   * `account_id` or `email_address` is required, If both are provided, the account id prevails.   Email address of the user to invite to your Team.
   */
  "emailAddress"?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "accountId",
      baseName: "account_id",
      type: "string",
    },
    {
      name: "emailAddress",
      baseName: "email_address",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return TeamAddMemberRequest.attributeTypeMap;
  }
}
