/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

export class TeamRemoveMemberRequest {
  /**
   * The ID or email address of the Account to remove from your Team. The account ID prevails if both are provided.
   */
  "accountId"?: string;
  /**
   * The ID or email address of the Account to remove from your Team. The account ID prevails if both are provided.
   */
  "emailAddress"?: string;
  /**
   * The email address of an Account on this Team to receive all documents, templates, and API apps (if applicable) from the removed Account. If not provided, and on an Enterprise plan, this data will remain with the removed Account.  **Note**: Only available for Enterprise plans.
   */
  "newOwnerEmailAddress"?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "accountId",
      baseName: "account_id",
      type: "string",
    },
    {
      name: "emailAddress",
      baseName: "email_address",
      type: "string",
    },
    {
      name: "newOwnerEmailAddress",
      baseName: "new_owner_email_address",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return TeamRemoveMemberRequest.attributeTypeMap;
  }
}
