/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { TemplateResponseDocumentCustomField } from "./templateResponseDocumentCustomField";
import { TemplateResponseDocumentFieldGroup } from "./templateResponseDocumentFieldGroup";
import { TemplateResponseDocumentFormField } from "./templateResponseDocumentFormField";
import { TemplateResponseDocumentStaticField } from "./templateResponseDocumentStaticField";

export class TemplateResponseDocument {
  /**
   * Name of the associated file.
   */
  "name"?: string;
  /**
   * Document ordering, the lowest index is displayed first and the highest last (0-based indexing).
   */
  "index"?: number;
  /**
   * An array of Form Field Group objects.
   */
  "fieldGroups"?: Array<TemplateResponseDocumentFieldGroup>;
  /**
   * An array of Form Field objects containing the name and type of each named textbox and checkmark field.
   */
  "formFields"?: Array<TemplateResponseDocumentFormField>;
  /**
   * An array of Document Custom Field objects.
   */
  "customFields"?: Array<TemplateResponseDocumentCustomField>;
  /**
   * An array describing static overlay fields. <b>Note</b> only available for certain subscriptions.
   */
  "staticFields"?: Array<TemplateResponseDocumentStaticField> | null;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "index",
      baseName: "index",
      type: "number",
    },
    {
      name: "fieldGroups",
      baseName: "field_groups",
      type: "Array<TemplateResponseDocumentFieldGroup>",
    },
    {
      name: "formFields",
      baseName: "form_fields",
      type: "Array<TemplateResponseDocumentFormField>",
    },
    {
      name: "customFields",
      baseName: "custom_fields",
      type: "Array<TemplateResponseDocumentCustomField>",
    },
    {
      name: "staticFields",
      baseName: "static_fields",
      type: "Array<TemplateResponseDocumentStaticField>",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return TemplateResponseDocument.attributeTypeMap;
  }
}
