/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { TemplateResponseDocumentCustomFieldAvgTextLength } from "./templateResponseDocumentCustomFieldAvgTextLength";

/**
 * An array of the designated CC roles that must be specified when sending a SignatureRequest using this Template.
 */
export class TemplateResponseDocumentCustomField {
  /**
   * The name of the Custom Field.
   */
  "name"?: string;
  /**
   * The type of this Custom Field. Only `text` and `checkbox` are currently supported.
   */
  "type"?: TemplateResponseDocumentCustomField.TypeEnum;
  /**
   * The horizontal offset in pixels for this form field.
   */
  "x"?: number;
  /**
   * The vertical offset in pixels for this form field.
   */
  "y"?: number;
  /**
   * The width in pixels of this form field.
   */
  "width"?: number;
  /**
   * The height in pixels of this form field.
   */
  "height"?: number;
  /**
   * Boolean showing whether or not this field is required.
   */
  "required"?: boolean;
  /**
   * The name of the group this field is in. If this field is not a group, this defaults to `null`.
   */
  "group"?: string | null;
  "avgTextLength"?: TemplateResponseDocumentCustomFieldAvgTextLength;
  /**
   * Use `form_fields` under the `documents` array instead.
   */
  "namedFormFields"?: object | null;
  "reusableFormId"?: string | null;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "type",
      baseName: "type",
      type: "TemplateResponseDocumentCustomField.TypeEnum",
    },
    {
      name: "x",
      baseName: "x",
      type: "number",
    },
    {
      name: "y",
      baseName: "y",
      type: "number",
    },
    {
      name: "width",
      baseName: "width",
      type: "number",
    },
    {
      name: "height",
      baseName: "height",
      type: "number",
    },
    {
      name: "required",
      baseName: "required",
      type: "boolean",
    },
    {
      name: "group",
      baseName: "group",
      type: "string",
    },
    {
      name: "avgTextLength",
      baseName: "avg_text_length",
      type: "TemplateResponseDocumentCustomFieldAvgTextLength",
    },
    {
      name: "namedFormFields",
      baseName: "named_form_fields",
      type: "object",
    },
    {
      name: "reusableFormId",
      baseName: "reusable_form_id",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return TemplateResponseDocumentCustomField.attributeTypeMap;
  }
}

export namespace TemplateResponseDocumentCustomField {
  export enum TypeEnum {
    Text = "text",
    Checkbox = "checkbox",
  }
}
