/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

export class TemplateResponseDocumentStaticField {
  /**
   * The name of the static field.
   */
  "name"?: string;
  /**
   * The type of this static field. See [field types](/api/reference/constants/#field-types).
   */
  "type"?: string;
  /**
   * The signer of the Static Field.
   */
  "signer"?: string;
  /**
   * The horizontal offset in pixels for this static field.
   */
  "x"?: number;
  /**
   * The vertical offset in pixels for this static field.
   */
  "y"?: number;
  /**
   * The width in pixels of this static field.
   */
  "width"?: number;
  /**
   * The height in pixels of this static field.
   */
  "height"?: number;
  /**
   * Boolean showing whether or not this field is required.
   */
  "required"?: boolean;
  /**
   * A unique id for the static field.
   */
  "apiId"?: string;
  /**
   * The name of the group this field is in. If this field is not a group, this defaults to `null`.
   */
  "group"?: string | null;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "type",
      baseName: "type",
      type: "string",
    },
    {
      name: "signer",
      baseName: "signer",
      type: "string",
    },
    {
      name: "x",
      baseName: "x",
      type: "number",
    },
    {
      name: "y",
      baseName: "y",
      type: "number",
    },
    {
      name: "width",
      baseName: "width",
      type: "number",
    },
    {
      name: "height",
      baseName: "height",
      type: "number",
    },
    {
      name: "required",
      baseName: "required",
      type: "boolean",
    },
    {
      name: "apiId",
      baseName: "api_id",
      type: "string",
    },
    {
      name: "group",
      baseName: "group",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return TemplateResponseDocumentStaticField.attributeTypeMap;
  }
}
