/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";

/**
 * An array of Form Field objects containing the name and type of each named textbox and checkmark field.
 */
export class TemplateResponseDocumentFormField {
  /**
   * A unique id for the form field.
   */
  "apiId"?: string;
  /**
   * The name of the form field.
   */
  "name"?: string;
  /**
   * The type of this form field. See [field types](/api/reference/constants/#field-types).
   */
  "type"?: TemplateResponseDocumentFormField.TypeEnum;
  /**
   * The horizontal offset in pixels for this form field.
   */
  "x"?: number;
  /**
   * The vertical offset in pixels for this form field.
   */
  "y"?: number;
  /**
   * The width in pixels of this form field.
   */
  "width"?: number;
  /**
   * The height in pixels of this form field.
   */
  "height"?: number;
  /**
   * Boolean showing whether or not this field is required.
   */
  "required"?: boolean;
  /**
   * The name of the group this field is in. If this field is not a group, this defaults to `null`.
   */
  "group"?: string | null;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "apiId",
      baseName: "api_id",
      type: "string",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "type",
      baseName: "type",
      type: "TemplateResponseDocumentFormField.TypeEnum",
    },
    {
      name: "x",
      baseName: "x",
      type: "number",
    },
    {
      name: "y",
      baseName: "y",
      type: "number",
    },
    {
      name: "width",
      baseName: "width",
      type: "number",
    },
    {
      name: "height",
      baseName: "height",
      type: "number",
    },
    {
      name: "required",
      baseName: "required",
      type: "boolean",
    },
    {
      name: "group",
      baseName: "group",
      type: "string",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return TemplateResponseDocumentFormField.attributeTypeMap;
  }
}

export namespace TemplateResponseDocumentFormField {
  export enum TypeEnum {
    Checkbox = "checkbox",
    CheckboxMerge = "checkbox-merge",
    DateSigned = "date_signed",
    Dropdown = "dropdown",
    Hyperlink = "hyperlink",
    Initials = "initials",
    Signature = "signature",
    Radio = "radio",
    Text = "text",
    TextMerge = "text-merge",
  }
}
