/**
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile, AttributeTypeMap } from "./models";
import { TemplateResponseDocumentCustomField } from "./templateResponseDocumentCustomField";
import { TemplateResponseDocumentFieldGroup } from "./templateResponseDocumentFieldGroup";
import { TemplateResponseDocumentFormField } from "./templateResponseDocumentFormField";

/**
 * An array describing each document associated with this Template. Includes form field data for each document.
 */
export class TemplateResponseDocument {
  /**
   * Name of the associated file.
   */
  "name"?: string;
  /**
   * Document ordering, the lowest index is displayed first and the highest last.
   */
  "index"?: number;
  "fieldGroups"?: Array<TemplateResponseDocumentFieldGroup>;
  "formFields"?: Array<TemplateResponseDocumentFormField>;
  "customFields"?: Array<TemplateResponseDocumentCustomField>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: AttributeTypeMap = [
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "index",
      baseName: "index",
      type: "number",
    },
    {
      name: "fieldGroups",
      baseName: "field_groups",
      type: "Array<TemplateResponseDocumentFieldGroup>",
    },
    {
      name: "formFields",
      baseName: "form_fields",
      type: "Array<TemplateResponseDocumentFormField>",
    },
    {
      name: "customFields",
      baseName: "custom_fields",
      type: "Array<TemplateResponseDocumentCustomField>",
    },
  ];

  static getAttributeTypeMap(): AttributeTypeMap {
    return TemplateResponseDocument.attributeTypeMap;
  }
}
