#!/usr/bin/env bash

# see https://github.com/OpenAPITools/openapi-generator/tree/1314e229f58cf056850dc912bbf55e49bcda2db8/modules/openapi-generator/src/main/resources/typescript-node

set -e

WORKINGDIR="/app/javascript"

docker run --rm \
  -v "${PWD}/:/local" \
  openapitools/openapi-generator-cli:v5.3.0 generate \
    -i "/local/oas/openapi-sdk.yaml" \
    -c "/local/openapi-config.yaml" \
    -t "/local/templates" \
    -o "/local/"

printf "\nInstalling composer dependencies ...\n"
mkdir -p "${PWD}/vendor"
bash "${PWD}/bin/php" composer install
printf "\n"

printf "Adding examples to /examples ...\n"
rm -f "${PWD}/examples/"*.js
rm -f "${PWD}/examples/"*.ts
cp -r "${PWD}/oas/examples/"*.js "${PWD}/examples/"
cp -r "${PWD}/oas/examples/"*.ts "${PWD}/examples/"

printf "Adding examples to Docs ...\n"
bash "${PWD}/bin/php" ./bin/generate-examples.php

printf "Install NPM dependencies ...\n"
mkdir -p "${PWD}/node_modules"
bash "${PWD}/bin/node" npm install

printf "Running prettier ...\n"
# bash "${PWD}/bin/node" npm run prettier

printf "Replacing strings ...\n"
docker run --rm \
  -v "${PWD}:${WORKINGDIR}" \
  -w "${WORKINGDIR}" \
  perl bash ./bin/replace

printf "Scanning for prohibited keywords ...\n"
docker run --rm \
  -v "${PWD}:${WORKINGDIR}" \
  -w "${WORKINGDIR}" \
  perl bash ./bin/scan_for

printf "Running build ...\n"
bash "${PWD}/bin/node" npm run build

printf "Running tests ...\n"
bash "${PWD}/bin/node" npm run test

printf "Success!\n"
