#!/usr/bin/env bash

# see https://github.com/OpenAPITools/openapi-generator/tree/1314e229f58cf056850dc912bbf55e49bcda2db8/modules/openapi-generator/src/main/resources/typescript-node

set -e

DIR=$(cd `dirname $0` && pwd)
WORKING_DIR="/app/javascript"

# Generate code
docker run --rm \
  -v "${DIR}/:/local" \
  --user "$(id -u):$(id -g)" \
  openapitools/openapi-generator-cli:v5.3.0 generate \
    -i "/local/openapi-sdk.yaml" \
    -c "/local/openapi-config.yaml" \
    -t "/local/templates" \
    -o "/local/" \
    --global-property=api=true \
    --global-property=model=true \
    --global-property=apiDocs=false \
    --global-property=modelDocs=false

# Generate API docs
rm -rf "${DIR}/docs/api" "${DIR}/tmp_docs"
mkdir -p "${DIR}/docs/api"
mkdir -p "${DIR}/tmp_docs"
docker run --rm \
  -v "${DIR}/:/local" \
  --user "$(id -u):$(id -g)" \
  openapitools/openapi-generator-cli:v5.3.0 generate \
    -i "/local/openapi-sdk.yaml" \
    -c "/local/openapi-config.yaml" \
    -t "/local/templates" \
    -o "/local/tmp_docs" \
    --global-property=api=false \
    --global-property=model=false \
    --global-property=apiDocs=true \
    --global-property=modelDocs=false

# Only need README.md from initial run
rm -f "${DIR}/tmp_docs/README.md"
mv "${DIR}/tmp_docs/"*.md "${DIR}/docs/api/"

# Generate Model docs
rm -rf "${DIR}/docs/model" "${DIR}/tmp_docs"
mkdir -p "${DIR}/docs/model"
mkdir -p "${DIR}/tmp_docs"
docker run --rm \
  -v "${DIR}/:/local" \
  --user "$(id -u):$(id -g)" \
  openapitools/openapi-generator-cli:v5.3.0 generate \
    -i "/local/openapi-sdk.yaml" \
    -c "/local/openapi-config.yaml" \
    -t "/local/templates" \
    -o "/local/tmp_docs" \
    --global-property=api=false \
    --global-property=model=false \
    --global-property=apiDocs=false \
    --global-property=modelDocs=true

# Only need README.md from initial run
rm -f "${DIR}/tmp_docs/README.md"
mv "${DIR}/tmp_docs/"*.md "${DIR}/docs/model/"
rm -rf "${DIR}/tmp_docs"

printf "\nInstalling composer dependencies ...\n"
mkdir -p "${DIR}/vendor"
bash "${DIR}/bin/php" composer install
printf "\n"

printf "Adding examples to Docs ...\n"
bash "${DIR}/bin/php" ./bin/generate-examples.php

printf "Install NPM dependencies ...\n"
mkdir -p "${DIR}/node_modules"
bash "${DIR}/bin/node" npm install

printf "Running prettier ...\n"
bash "${DIR}/bin/node" npm run prettier

printf "Replacing strings ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/replace

printf "Scanning for prohibited keywords ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/scan_for

printf "Running build ...\n"
bash "${DIR}/bin/node" npm run build
bash "${DIR}/bin/node" npm run build-types

printf "Running tests ...\n"
bash "${DIR}/bin/node" npm run test

printf "Success!\n"
